const swears = [
    "fuck",
    "fock",
    "fuk",
    "fucker",
    "fokrt",
    "fker",
    "f4uk",
    "fuk",
    "bitch",
    "b!tch",
    "b!t@h",
    "ass",
    "a$$",
    "@$$",
    "nigger",
    "nogger",
    "n!gger",
    "n1gger",
    "retard",
    "kys",
    "hang yourself",
    "anus",
    "sex",
    "s3x",
    "pussy",
    "pussie",
    "anal",
    "ballsack",
    "bastard",
    "blowjob",
    "blow job",
    "bollock",
    "bollok",
    "boner",
    "boob",
    "buttplug",
    "clitoris",
    "cock",
    "coon",
    "cunt",
    "f u c k",
    "dick",
    "dildo",
    "fag",
    "faggot",
    "nigga",
    "nibba",
    "wank",
    "penis",
    "shit",
    "fappy",
    "f4ppy",
    "@ss",
    "dic"
];

function checkSwears(content) {
    const split = content.toLowerCase().split(" ");
    return !!swears.find(swear => split.includes(swear));
}

module.exports = checkSwears;
